name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kustomize version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Test changes to download URL format with specific versions
      - name: Test plugin (kustomize 3.2.1)
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 3.2.1
          command: kustomize version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test plugin (kustomize 3.2.0)
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 3.2.0
          command: kustomize version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
