name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: kustomize version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Test changes to download URL format with specific versions
      - name: asdf_plugin_test_3_2_1
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          version: 3.2.1
          command: kustomize version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: asdf_plugin_test_3_2_0
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          version: 3.2.0
          command: kustomize version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
